[package]
name = "amm"
kind = "contract"

[dependencies]
std = { path = "../std" }  # Adjusted path to reflect the relative position of `std`

[contract-dependencies]
# Add any contract-specific dependencies if applicable

